name: league_repository
description: Dart package which manages the league domain.
version: 1.0.0
publish_to: none


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.2.0
  get_it: ^6.0.0
  freezed: ^0.14.0+1
  freezed_annotation: ^0.14.0
  json_serializable: ^4.0.2
  profanity_filter: ^1.0.4
  uuid: ^3.0.1
  equatable: ^1.2.5
  rxdart: ^0.26.0
  cloud_firestore: ^0.16.0+1
  firebase_core: ^0.7.0
  firebase_core_web: ^0.2.1+3
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.1
  dartz: 0.10.0-nullsafety.1
  meta:
  user_repository:
    git:
      url: https://github.com/flaktest/flaktestAuth.git
      ref: main

dev_dependencies:
  build_runner: ^1.10.1
  auto_route_generator: ^0.6.10
  injectable_generator: ^1.2.0
  lint: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

