name: league_repository
description: Dart package which manages the league domain.
version: 1.0.0


environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  injectable:
  get_it:
  freezed_annotation:
  json_serializable:
  profanity_filter:
  uuid:
  equatable:
  rxdart:
  dartz:
  cloud_firestore:
  firebase_auth:
  firebase_core:
  meta:
  user_repository:
    git:
      url: https://github.com/flaktest/flaktestAuth.git
      ref: main

dev_dependencies:
  build_runner:
  analyzer:
  injectable_generator:
  lint:
  freezed:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

