name: league_repository
description: Dart package which manages the league domain.
version: 1.0.0
publish_to: none


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #Firebase & Firestore plugins - Null Safe
  firebase_core: ^1.0.2
  firebase_core_web: ^1.0.2
  firebase_analytics: ^8.0.0-dev.0
  firebase_auth: ^1.0.1
  firebase_dynamic_links: ^2.0.0-dev.0
  cloud_firestore: ^1.0.3
  cloud_functions: ^1.0.2
  #############
  flutter_bloc: ^7.0.0 #Flutter Bloc - Null Safe
  dartz: 0.10.0-nullsafety.1 #Functional Programming in Dart
  datetime_picker_formfield: ^2.0.0 #Date Time Picker - Null Safe
  shared_preferences: ^2.0.5 #Shared Preferences - Null Safe
  google_fonts: ^2.0.0 #Google - Null Safe
  auto_route: ^1.0.2 #auto_route - Null Safe
  flutter_hooks: ^0.16.0  #flutter_hooks - Null Safe
  injectable: ^1.2.2 #Injectable - Null Safe
  get_it: ^6.0.0-nullsafety.1 #Injectable - Null Safe
  freezed: ^0.14.0+1 #Freezed - Null Safe
  freezed_annotation: ^0.14.0 #Freezed Annotation - Null Safe
  json_annotation: ^4.0.0 #Json Annotation - Null Safe
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0-nullsafety.11  #Screen Util- Null Safe
  profanity_filter: ^2.0.0-nullsafety.0
  uuid: ^3.0.2
  rxdart: ^0.26.0
  user_repository:
    git:
      url: https://github.com/flaktest/flaktestAuth.git
      ref: main

dev_dependencies:
  build_runner: ^1.10.1
  auto_route_generator: ^1.0.2
  injectable_generator: ^1.2.2
  json_serializable: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

